# permissions for end users to view testops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testop-viewer-role
rules:
- apiGroups:
  - hello.example.com
  resources:
  - testops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.example.com
  resources:
  - testops/status
  verbs:
  - get
